#!/bin/bash

# This is a simple script that will take pictures with raspistill
# and will store them on the folder PICS_DIR defined below.
# The script automatically cleans the older pictures from the same
# folder, keeping MAX_PICS number of pictures stored on the folder.
#
# The script will also generate a small GIF animation with the JPEG
# images it has taken. Also a .log file will be created with every
# picture with information like temperatures, uptime, etc...
#
# Make sure you only use this folder for this script, or you may
# lose other files during cleanup.
#
# The best output folder for this script on the Raspberry Pi is
# a tmpfs folder (folder in RAM) as it avoids write cycles on the
# SD card.
# For example, this is my entry in /etc/fstab:
# tmpfs /var/www/html/img tmpfs defaults,noatime,gid=1000, \
#                               uid=1000,nodev,noexec,mode=0755, \
#                               size=50M 0 0
#
# If you have a webserver, you can also set a tmpfs folder under
# /var/www/html so you can access the last X pictures from your
# browser.
#
# You can copy this file to /usr/local/bin and give 755 permitions,
# so it can be called straight from the terminal at any place.
#
# You should add this script to crontab so it runs automatically.
# For example this is my entry in crontab:
# */10 * * * * /bin/bash -c "/usr/local/bin/camlapse" \
#                           >> /var/www/html/img/camlapse.txt 2>&1
#
# Make sure you have installed ImageMagik for the creation of the
# GIF animation
#

# The directory where the pictures will be saved:
PICS_DIR="/var/www/html/img"

# The maximum number of pictures to keep on the folder:
MAX_PICS=24

# The raspistill parameters (excluding -o)
RASPISTILL_PARAMS="-w 800 -h 600 -drc high -ex night -a 12 -q 20 -sh 50 -th 160:120:10"

TIME_HUM=$(date)
TIME_NOW=$(date +"%s")

# Check if there is a raspistill already running:
PID_RASPISTILL=$(pidof raspistill)
if [ ! -z "$PID_RASPISTILL" ]
then
    echo "Raspistill already running. Trying again in 5 seconds"
    sleep 5
fi

echo "Taking picture and storing statistics at $TIME_HUM"
raspistill -o $PICS_DIR/$TIME_NOW.jpg $RASPISTILL_PARAMS

# Fill statistics:
CPU_TEMP=$(vcgencmd measure_temp | cut -d"=" -f2 | cut -d"'" -f1)
IN_TEMP="0.00"
OUT_TEMP="0.00"
UPTIME=$(awk '{print $1}' /proc/uptime | cut -d'.' -f1)
echo "CPU_TEMP=$CPU_TEMP" >> $PICS_DIR/$TIME_NOW.log
echo "IN_TEMP=$IN_TEMP" >> $PICS_DIR/$TIME_NOW.log
echo "OUT_TEMP=$OUT_TEMP" >> $PICS_DIR/$TIME_NOW.log
echo "UPTIME=$UPTIME" >> $PICS_DIR/$TIME_NOW.log
echo "TIME_NOW=$TIME_NOW" >> $PICS_DIR/$TIME_NOW.log

# Create small GIF animation:
convert -delay 50 -loop 0 -resize 30% -layers Optimize $PICS_DIR/*.jpg $PICS_DIR/animation.gif

# Remove older pictures:
TOTAL_PICS=$(ls $PICS_DIR/*.jpg | wc -l)
if [ "$TOTAL_PICS" -gt "$MAX_PICS" ]
then
	OLDEST_TIME=$(ls $PICS_DIR/*.jpg | head -n1 | cut -d'.' -f1)
	rm -rf $OLDEST_TIME.*
fi
